spring.application.name=arp

server.port=8080

server.servlet.context.path=/api/
#Swagger-ui custom configs
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Database setup
spring.datasource.url=jdbc:postgresql://137.184.136.186:5432/bd_principal
spring.datasource.username=usuario_compartido
spring.datasource.password=T7#xR4!vQz9@mLp2

# Hibernate (JPA) setup
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update